# Generated by Django 3.0.4 on 2020-09-10 19:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75)),
                ('description', models.TextField()),
                ('cause', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=150)),
                ('volunteers_required', models.IntegerField(default=1)),
                ('duration', models.CharField(max_length=20)),
                ('event_timings', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_complete', models.BooleanField(default=False)),
                ('slug', models.SlugField(default='event_name')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL)),
                ('volunteers', models.ManyToManyField(related_name='volunteers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
