# Generated by Django 3.0.4 on 2020-09-11 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('BankTransfer', 'BankTransfer'), ('PayTM', 'PayTM'), ('GooglePay', 'GooglePay'), ('CreditCard', 'CreditCard'), ('DebitCard', 'DebitCard')], max_length=12),
        ),
    ]
