# Generated by Django 3.0.4 on 2020-09-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_donation_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donation',
            name='payment_method',
            field=models.CharField(choices=[('BankTransfer', 'BankTransfer'), ('PayTM', 'PayTM'), ('GooglePay', 'GooglePay'), ('CreditCard', 'CreditCard'), ('DebitCard', 'DebitCard')], editable=False, max_length=12),
        ),
    ]
