# Generated by Django 3.0.4 on 2020-09-12 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200911_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='volunteers',
            new_name='volunteer',
        ),
    ]
