# Generated by Django 3.0.4 on 2020-09-12 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200912_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='volunteer',
            new_name='volunteers',
        ),
    ]
